title: Alex Falcon
description: Credits to Jorge Sanz for the template "gh-pages-minima-starter" 
author: Alex Falcon

theme: minima

# base_url: /gh-pages-minima-starter

# Minima social links
github_username: aranciokov
linkedin_username: alex-falcon-9b1a231a3

# Minima: show excerpts in the frontpage
# show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
